#!/usr/bin/env python3
"""Generate lib/core/encoding/cp949_table.g.dart from Python's cp949 codec.

Two-byte table: lead 0x81..0xFE x trail 0x41..0xFE, row-major. Unmapped
pairs are U+FFFD. Run from the repo root; do not edit the output by hand.
"""
import pathlib

LEADS = range(0x81, 0xFF)
TRAILS = range(0x41, 0xFF)

chars = []
for lead in LEADS:
    for trail in TRAILS:
        try:
            s = bytes([lead, trail]).decode("cp949")
            chars.append(s if len(s) == 1 else "�")
        except UnicodeDecodeError:
            chars.append("�")

lines = []
for i in range(0, len(chars), 95):
    chunk = "".join(chars[i : i + 95])
    chunk = chunk.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$")
    lines.append(f"    '{chunk}'")

out = pathlib.Path("lib/core/encoding/cp949_table.g.dart")
out.write_text(
    "// GENERATED by tool/encoding/generate_cp949.py — do not edit.\n"
    "// ignore_for_file: prefer_single_quotes\n\n"
    "const int cp949LeadMin = 0x81;\n"
    "const int cp949LeadMax = 0xFE;\n"
    "const int cp949TrailMin = 0x41;\n"
    "const int cp949TrailMax = 0xFE;\n\n"
    "/// Row-major (lead, trail) -> character; U+FFFD when unmapped.\n"
    "const String cp949Table =\n" + "\n".join(lines) + ";\n",
    encoding="utf-8",
)
print(len(chars), "entries")
